/** Query keys in one place so realtime sync and hooks never drift apart. */
export const keys = {
  health: ['health'] as const,
  overview: ['overview'] as const,
  tasksRoot: ['tasks'] as const,
  tasks: (filters: Record<string, string | undefined>) => ['tasks', filters] as const,
  task: (id: string) => ['task', id] as const,
  taskEvents: (id: string) => ['task', id, 'events'] as const,
  taskExecutions: (id: string) => ['task', id, 'executions'] as const,
  taskTests: (id: string) => ['task', id, 'tests'] as const,
  taskArtifacts: (id: string) => ['task', id, 'artifacts'] as const,
  taskChanges: (id: string) => ['task', id, 'changes'] as const,
  taskDiff: (id: string, path: string | null) => ['task', id, 'diff', path ?? '*'] as const,
  taskDirectives: (id: string) => ['task', id, 'directives'] as const,
  taskApprovals: (id: string) => ['task', id, 'approvals'] as const,
  logs: (executionId: string) => ['logs', executionId] as const,
  artifactContent: (id: string) => ['artifact', id] as const,
  approvals: (status: 'pending' | 'all') => ['approvals', status] as const,
  agents: ['agents'] as const,
  repositories: ['repositories'] as const,
  repository: (id: string) => ['repository', id] as const,
  workflows: ['workflows'] as const,
  workflow: (id: string) => ['workflow', id] as const,
  settings: ['settings'] as const,
  prompts: ['prompts'] as const,
};
